[package]
name = "carbon14"
version = "0.0.0"
edition = "2021"
license = "MIT"
authors = ["Gabriel Falcão <gabriel@nacaolivre.org>"]
description = ""
documentation = "https://docs.rs/carbon14"
readme = "README.md"
homepage = "https://github.com/gabrielfalcao/carbon14"


[dependencies]
adler32 = { version = "1.2.0", features = ["core"] }
base64 = "0.21.5"
clap = { version = "4.4.6", features = ["derive"] }
copypasta = "0.10.0"
crc = "3.0.1"
hex = { version = "0.4.3", features = ["serde"] }
indicatif = "0.17.7"
iocore = "0.110.0"
md5 = "0.7.0"
serde = { version = "1.0.190", features = ["alloc", "derive", "rc", "serde_derive"] }
serde_json = { version = "1.0.108", features = ["alloc", "std", "float_roundtrip", "arbitrary_precision", "indexmap", "preserve_order"] }
serde_yaml = "0.9.27"
sha = "1.0.3"
sha2 = { version = "0.10.8", features = ["oid", "compress"] }
sha3 = { version = "0.10.8", features = ["std", "asm", "reset", "oid"] }



[[bin]]
name = "carbon14"
path = "src/main.rs"
bench = false

[lib]
name = "carbon14"
path = "src/lib.rs"

[dev-dependencies]
k9 = "0.11.6"
