name: "Continuous Integration"

on:
  - push
  - pull_request

env:
  CARGO_TERM_COLOR: "always"
jobs:
  ubuntu:
    strategy:
      matrix:
        target:
          - aarch64-apple-darwin
          - x86_64-apple-darwin
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
          - i586-unknown-linux-gnu
          - i686-unknown-linux-gnu
          - riscv64gc-unknown-linux-gnu

    name: Check, Build and Test (Ubuntu)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rust-src, rustc-dev, rustfmt
          target: ${{ matrix.target }}

      - name: check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: build
        uses: actions-rs/cargo@v1
        with:
          command: build
      - name: upload target artifacts
        uses: actions/upload-artifact@v4
        with:
          name: target-ubuntu
          path: target
      - name: test
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: doc
        uses: actions-rs/cargo@v1
        with:
          command: doc

      - name: upload executable
        uses: actions/upload-artifact@v4
        with:
          name: "target-${{ matrix.target }}"
          path: "target/carbon14"
